Repository depromeet/everybody-backend, pull requests merged in 2021-11, with the labels that each got.

#30 Query string으로 사진 리스트 조회하도록 변경
  rest-api/dto/picture.go
  rest-api/infra/http/handler/pictureHandler.go
  rest-api/infra/http/server.go
  rest-api/mocks/picture_service_interface.go
  rest-api/service/picture.go
  rest-api/service/picture_test.go
Labels: approved

#31 사진 업로드 API 구현 및 api-gateway 보완
  api-gateway/config/config.go
  api-gateway/config/sample.yml
  api-gateway/controller/auth.go
  api-gateway/controller/picture.go
  api-gateway/controller/restapi.go
  api-gateway/model/userauth.go
  api-gateway/util/jwt.go
Labels: approved

#32 앨범 및 사진의 리소스 접근 권한 로직 추가
  rest-api/infra/http/handler/albumHandler.go
  rest-api/infra/http/handler/pictureHandler.go
  rest-api/main.go
  rest-api/mocks/album_service_interface.go
  rest-api/mocks/picture_service_interface.go
  rest-api/repository/album.go
  rest-api/repository/picture.go
  rest-api/service/album.go
  rest-api/service/album_test.go
  rest-api/service/picture.go
  rest-api/service/picture_test.go
Labels: approved, need-discussion

#34 feat: 랜덤 닉네임, 기본 좌우명
  rest-api/README.md
  rest-api/config/config.go
  rest-api/dto/user.go
  rest-api/main.go
  rest-api/mocks/user_repository.go
  rest-api/repository/user.go
  rest-api/service/device.go
  rest-api/service/user.go
  rest-api/service/user_test.go
Labels: approved

#33 람다로 사진 업로드 할 때 timeout 설정
  uploader/handler.py
  uploader/sample_data.py
  uploader/serverless.yml
Labels: approved

#35 feat: 가장 안쪽 스택만 trace
  rest-api/go.mod
  rest-api/go.sum
  rest-api/infra/http/handler/albumHandler.go
  rest-api/infra/http/middleware.go
  rest-api/infra/routine/notification.go
  rest-api/service/error.go
  rest-api/service/error_test.go
  rest-api/service/picture.go
  rest-api/service/user.go
Labels: approved

#37 Feat: 앨범 조회 시 속한 사진 정보도 제공
  rest-api/config/config.go
  rest-api/config/sample.yml
  rest-api/dto/album.go
  rest-api/dto/picture.go
  rest-api/dto/user.go
  rest-api/ent/migrate/schema.go
  rest-api/ent/mutation.go
  rest-api/ent/picture.go
  rest-api/ent/picture/picture.go
  rest-api/ent/picture/where.go
  rest-api/ent/picture_create.go
  rest-api/ent/picture_update.go
  rest-api/ent/runtime.go
  rest-api/ent/schema/picture.go
  rest-api/ent/schema/user.go
  rest-api/ent/user.go
  rest-api/ent/user/user.go
  rest-api/ent/user/where.go
  rest-api/ent/user_create.go
  rest-api/ent/user_query.go
  rest-api/ent/user_update.go
  rest-api/go.sum
  rest-api/infra/http/middleware.go
  rest-api/repository/album.go
  rest-api/repository/picture.go
  rest-api/repository/user.go
  rest-api/service/album.go
  rest-api/service/picture.go
  rest-api/service/picture_test.go
  rest-api/service/user.go
  rest-api/service/user_test.go
  rest-api/util/util.go
  rest-api/util/util_test.go
Labels: approved

#36 feat: 가입 시 rest의 응답 전달, 사진 업로드 시 누락된 content-type 및 헤더들
  api-gateway/controller/auth.go
  api-gateway/controller/picture.go
  api-gateway/controller/restapi.go
  api-gateway/go.mod
  api-gateway/go.sum
  api-gateway/main.go
Labels: approved

#38 API Gateway 자잘한 픽스
  api-gateway/controller/restapi.go
  api-gateway/go.sum
  api-gateway/main.go
  api-gateway/util/jwt.go
Labels: bug, approved

#40 슬랙 에러 로그 전송
  rest-api/config/config.go
  rest-api/config/sample.yml
  rest-api/go.mod
  rest-api/go.sum
  rest-api/logger.go
  rest-api/logger_test.go
  rest-api/main.go
Labels: approved

#41 앨범 설명에 "%d일 간의 기록 추가"
  rest-api/dto/album.go
  rest-api/infra/http/middleware.go
  rest-api/service/device.go
  rest-api/service/error.go
  rest-api/service/error_test.go
  rest-api/service/picture.go
  rest-api/service/user.go
Labels: approved

#42 feat: 정기적 알림을 보낼 대상인지 판단하는 로직
  rest-api/adapter/push/fcm.go
  rest-api/ent/client.go
  rest-api/ent/migrate/schema.go
  rest-api/ent/mutation.go
  rest-api/ent/notificationconfig/where.go
  rest-api/ent/notificationconfig_create.go
  rest-api/ent/notificationconfig_query.go
  rest-api/ent/notificationconfig_update.go
  rest-api/ent/schema/user.go
  rest-api/ent/user.go
  rest-api/ent/user/where.go
  rest-api/ent/user_create.go
  rest-api/ent/user_query.go
  rest-api/ent/user_update.go
  rest-api/go.sum
  rest-api/infra/http/server.go
  rest-api/infra/routine/notification.go
  rest-api/service/notification.go
Labels: approved

#43 앨범 수정/삭제 사진 삭제 API, 에러 처리 로직 개선
  rest-api/dto/album.go
  rest-api/ent/migrate/schema.go
  rest-api/ent/schema/album.go
  rest-api/ent/schema/user.go
  rest-api/go.mod
  rest-api/go.sum
  rest-api/infra/http/handler/albumHandler.go
  rest-api/infra/http/handler/pictureHandler.go
  rest-api/infra/http/middleware.go
  rest-api/infra/http/server.go
  rest-api/logger_test.go
  rest-api/mocks/album_repository_interface.go
  rest-api/mocks/album_service_interface.go
  rest-api/mocks/picture_repository_interface.go
  rest-api/mocks/picture_service_interface.go
  rest-api/repository/album.go
  rest-api/repository/picture.go
  rest-api/service/album.go
  rest-api/service/album_test.go
  rest-api/service/device.go
  rest-api/service/error.go
  rest-api/service/picture.go
  rest-api/service/picture_test.go
  rest-api/service/user.go
  rest-api/util/util.go
Labels: approved

#44 api-gw 라우팅 오류 수정 외 일부 마이너 개선
  api-gateway/config/sample.yml
  api-gateway/controller/auth.go
  api-gateway/controller/index.go
  api-gateway/controller/picture.go
  api-gateway/controller/restapi.go
  api-gateway/main.go
  api-gateway/util/jwt.go
Labels: approved

#45 간단한 서버 상태 모니터링, 에러 로그 관찰 도구
  .ebextensions/additional-log-group.config
  .ebextensions/options.config
  rest-api/.ebextensions/files.config
  rest-api/.ebextensions/options.config
Labels: approved

#46 feat: 기본 알림 설정 적용
  rest-api/service/user.go
  rest-api/service/user_test.go
Labels: approved

#47 nginx 바디 사이즈 제한 완화
  .platform/nginx/conf.d/custom.conf
Labels: approved

#48 앨범 조회할 때 대표 썸네일 추가 및 신체부위 key로 하는 dto 보완
  rest-api/dto/album.go
  rest-api/service/album.go
  rest-api/service/picture.go
Labels: approved
